#!/bin/zsh

# Script to create tmux session suited for Python Django development.
# Nothing special, just creates a named session with specific pane splits.

if [ "$TERM_PROGRAM" = "tmux" ]
then
    printf "Exit current tmux session first!\n"
    exit 0
fi

SESSNAME="${1:=django-dev}"
tmux new-session -s $SESSNAME -d
tmux split-window -h
tmux resize-pane -t 0 -x 70
tmux split-window -t 0 -v
tmux resize-pane -t 0 -y 50 
tmux select-pane -t 0
tmux attach-session -d
